tengstrom_config_favicon.settings:
  type: config_object
  label: 'Tengström Configuration Favicon settings'
  mapping:
    uuid:
      type: uuid
      label: 'Uuid to favicon in managed file table'
