tengstrom_config_email_logo.settings:
  type: config_object
  label: 'Tengström Configuration Email Logo settings'
  mapping:
    uuid:
      type: uuid
      label: 'Uuid to email logo in managed file table'
