name: Tengström Configuration - Logo
package: Tengström Profile

type: module
core_version_requirement: ^9 || ^10

dependencies:
  - tengstrom_configuration:tengstrom_configuration
  - tengstrom_general:tengstrom_general

version: 0.1.0
