name: Tengström Configuration
package: Tengström Profile

type: module
core_version_requirement: ^9 || ^10

dependencies:
  - file_improvements:file_improvements
  - tengstrom_mainmenu:tengstrom_mainmenu

version: 0.1.0
