services:
  # Hook handlers
  tengstrom_configuration.hook_handlers.preprocess_image_widget:
    class: Drupal\tengstrom_configuration\HookHandlers\PreprocessHandlers\PreprocessImageWidgetHandler

  # Other services
  tengstrom_configuration.image_element_factory:
    class: Drupal\tengstrom_configuration\Factories\ImageElementFactory
    arguments:
      - '@string_translation'
      - '@tengstrom_general.entity_repository'
      - '@file_system'
