services:
  # Hook handlers
  tengstrom_config_email_logo.hook_handlers.tengstrom_config_form_alter:
    class: Drupal\tengstrom_config_email_logo\HookHandlers\FormAlterHandlers\TengstromConfigFormAlter
    arguments:
      - '@config.factory'
      - '@tengstrom_configuration.image_element_factory'
      - '@entity_type.manager'
      - '@string_translation'
      - '%tengstrom_configuration%'

  # Other services
  tengstrom_config_email_logo.file_loader:
    class: Drupal\tengstrom_config_email_logo\EmailLogoFileLoader
    arguments:
      - '@config.factory'
      - '@entity_type.manager'