name: Tengström Configuration - Favicon
package: Tengström Profile

type: module
core_version_requirement: ^10 || ^11

dependencies:
  - drupal:image
  - tengstrom_configuration:tengstrom_configuration

version: 0.1.0
