<?php

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_tengstrom_configuration_form_alter().
 */
function tengstrom_config_favicon_form_tengstrom_configuration_form_alter(array &$form, FormStateInterface $formState, string $formId): void {
  /** @var \Drupal\tengstrom_config_favicon\HookHandlers\FormAlterHandlers\TengstromConfigFormAlter $service */
  $service = \Drupal::service('tengstrom_config_favicon.hook_handlers.tengstrom_config_form_alter');

  $service->alter($form, $formState, $formId);
}
