services:
  # Hook handlers
  tengstrom_config_favicon.hook_handlers.tengstrom_config_form_alter:
    class: Drupal\tengstrom_config_favicon\HookHandlers\FormAlterHandlers\TengstromConfigFormAlter
    arguments:
      - '@config.factory'
      - '@tengstrom_configuration.image_element_factory'
      - '@entity_type.manager'
      - '@file.repository'
      - '@theme_handler'
      - '@string_translation'
      - '%tengstrom_configuration%'
